name: autumn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.18.0
  - geopandas=0.8.1
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.5
  - python=3.8.5
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - sphinx=3.4.0
  - sphinx-prompt=1.3.0
  - statsmodels=0.12.1
  - yaml=0.2.5
  - pip:
    - powerplantmatching==0.4.8

